In [14]:
import numpy as np

A = np.array([1, 2, 3, 4])
print("A : ", A, "\nA dimension : ", np.ndim(A), "\nA shape : ", A.shape)

A :  [1 2 3 4] 
A dimension :  1 
A shape :  (4,)


In [12]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print("B :\n", B, "\nB dimension : ", np.ndim(B), "\nB shape : ", B.shape)

B :
 [[1 2]
 [3 4]
 [5 6]] 
B dimension :  2 
B shape :  (3, 2)


In [17]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
print("A shape = ", A.shape, "B shape = ", B.shape)
print(np.dot(A, B))

A shape =  (2, 3) B shape =  (3, 2)
[[22 28]
 [49 64]]


In [19]:
C = np.array([[1, 2], [3, 4]])
print("A shape = ", A.shape, "C shape = ", C.shape)
print(np.dot(A, C))

A shape =  (2, 3) C shape =  (2, 2)


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [20]:
D = np.array([7, 8])
print("A shape = ", A.shape, "D shape = ", D.shape)
print(np.dot(D, A))   # 알아서 계산이 되도록 행렬 shape를 변환해준다

A shape =  (2, 3) D shape =  (2,)
[39 54 69]
